### ISSUE TITLE
 Error: Rule can only have one resource source (provided resource and test + include + exclude) in 6.0.0

### ISSUE THREAD

**Issue by stefpb** [JetBrains/svg-sprite-loader#443]
**Do you want to request a feature, report a bug or ask a question?**

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/1069441/111138449-3b2c5000-8580-11eb-8a10-41f09da690a7.png)
`[webpack-cli] Error: Rule can only have one resource source (provided resource and test + include + exclude) in {
  "enforce": "pre",
  "loader": "eslint-loader",
  "options": {
    "configFile": "./.eslintrc.js"
  },
  "exclude": [
    {},
    "/var/www/html/assets/Yves/shared/img"
  ],
  "include": [
    "/var/www/html/assets/Yves/opus/app",
    "/var/www/html/assets/Yves/shared"
  ]
}
    at checkResourceSource (/var/www/html/node_modules/webpack/lib/RuleSet.js:167:11)
    at Function.normalizeRule (/var/www/html/node_modules/webpack/lib/RuleSet.js:198:4)
    at /var/www/html/node_modules/webpack/lib/RuleSet.js:110:20
    at Array.map (<anonymous>)
    at Function.normalizeRules (/var/www/html/node_modules/webpack/lib/RuleSet.js:109:17)
    at new RuleSet (/var/www/html/node_modules/webpack/lib/RuleSet.js:104:24)
    at module.exports (/var/www/html/assets/node_modules/svg-sprite-loader/lib/utils/get-matched-rule-4.js:15:21)
    at SVGSpritePlugin.apply (/var/www/html/assets/node_modules/svg-sprite-loader/lib/plugin.js:61:18)
    at createCompiler (/var/www/html/assets/node_modules/webpack/lib/webpack.js:71:12)
    at create (/var/www/html/assets/node_modules/webpack/lib/webpack.js:118:16) 
    at webpack (/var/www/html/assets/node_modules/webpack/lib/webpack.js:126:47)
    at WebpackCLI.f [as webpack] (/var/www/html/assets/node_modules/webpack/lib/index.js:41:15)
    at WebpackCLI.createCompiler (/var/www/html/assets/node_modules/webpack-cli/lib/webpack-cli.js:1678:29)
    at WebpackCLI.buildCommand (/var/www/html/assets/node_modules/webpack-cli/lib/webpack-cli.js:1785:20)
    at Command.<anonymous> (/var/www/html/assets/node_modules/webpack-cli/lib/webpack-cli.js:564:25)
    at async Promise.all (index 1)
error Command failed with exit code 2.`

**What is the expected behavior?**
Webpack runs through.

**If the current behavior is a bug, please provide the steps to reproduce, at least part of webpack config with loader configuration and piece of your code.**
**The best way is to create repo with minimal setup to demonstrate a problem (package.json, webpack config and your code).**
**It you don't want to create a repository - create a [gist](http://gist.github.com) with multiple files**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please tell us about your environment:**

- Node.js version: 14.10.1
- webpack version: 5.25.1
- svg-sprite-loader version: 6.0.0 
- OS type & version: 20.04.1-Ubuntu (inside Docker)

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**
Downgrade svg-sprite-loader to 5.2.1 solve this problem, but than i have deprecated warnings.

**Comment by d3x42** [comment]
Could you please provide a git report with the same reproduced issue?

**Comment by stefpb** [comment]
I updated to 6.0.2 and rerun webpack again and i get the same error:

![image](https://user-images.githubusercontent.com/1069441/111683334-9e8adc00-8825-11eb-9153-2fb9ad9cc0f4.png)

```
$ NODE_ENV=production THEME=opus webpack --config=./webpack/webpack.prod.babel.js --mode production
[webpack-cli] Error: Rule can only have one resource source (provided resource and test + include + exclude) in {
  "include": [
    "/var/www/html/assets/Yves/opus",
    "/var/www/html/assets/Yves/shared"
  ],
  "exclude": {},
  "use": [
    {
      "loader": "babel-loader",
      "options": {
        "cacheDirectory": true
      },
      "ident": "clonedRuleSet-1[0].rules[0]"
    }
  ]
}
    at checkResourceSource (/var/www/html/node_modules/webpack/lib/RuleSet.js:167:11)
    at Function.normalizeRule (/var/www/html/node_modules/webpack/lib/RuleSet.js:198:4)
    at /var/www/html/node_modules/webpack/lib/RuleSet.js:110:20
    at Array.map (<anonymous>)
    at Function.normalizeRules (/var/www/html/node_modules/webpack/lib/RuleSet.js:109:17)
    at new RuleSet (/var/www/html/node_modules/webpack/lib/RuleSet.js:104:24)
    at module.exports (/var/www/html/assets/node_modules/svg-sprite-loader/lib/utils/get-matched-rule-4.js:15:21)
    at SVGSpritePlugin.apply (/var/www/html/assets/node_modules/svg-sprite-loader/lib/plugin.js:61:18)
    at createCompiler (/var/www/html/assets/node_modules/webpack/lib/webpack.js:71:12)
    at create (/var/www/html/assets/node_modules/webpack/lib/webpack.js:118:16)
    at webpack (/var/www/html/assets/node_modules/webpack/lib/webpack.js:126:47)
    at WebpackCLI.f [as webpack] (/var/www/html/assets/node_modules/webpack/lib/index.js:41:15)
    at WebpackCLI.createCompiler (/var/www/html/assets/node_modules/webpack-cli/lib/webpack-cli.js:1678:29)
    at WebpackCLI.buildCommand (/var/www/html/assets/node_modules/webpack-cli/lib/webpack-cli.js:1785:20)
    at Command.<anonymous> (/var/www/html/assets/node_modules/webpack-cli/lib/webpack-cli.js:564:25)
    at async Promise.all (index 1)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

In the meantime i replaced eslint-loader to eslint-webpack-plugin. With the svg-sprite-loader v5.2.1 it runs through, but there i get 
```
(node:1792) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
    at getNormalModuleLoader (/var/www/html/assets/node_modules/webpack/lib/Compilation.js:333:39)
    at Object.get normalModuleLoader [as normalModuleLoader] (/var/www/html/assets/node_modules/webpack/lib/Compilation.js:753:12)
    at /var/www/html/assets/node_modules/svg-sprite-loader/lib/plugin.js:74:14
    at Hook.eval (eval at create (/var/www/html/assets/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:12:1)
    at Hook.CALL_DELEGATE [as _call] (/var/www/html/assets/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/var/www/html/assets/node_modules/webpack/lib/Compiler.js:992:30)
    at /var/www/html/assets/node_modules/webpack/lib/Compiler.js:1035:29
    at Hook.eval [as callAsync] (eval at create (/var/www/html/assets/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/var/www/html/assets/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/var/www/html/assets/node_modules/webpack/lib/Compiler.js:1030:28)
    at /var/www/html/assets/node_modules/webpack/lib/Compiler.js:473:12
    at Compiler.readRecords (/var/www/html/assets/node_modules/webpack/lib/Compiler.js:871:11)
    at /var/www/html/assets/node_modules/webpack/lib/Compiler.js:470:11
    at eval (eval at create (/var/www/html/assets/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:19:1)
    at /var/www/html/assets/node_modules/stylelint-webpack-plugin/dist/linter.js:73:7
```.
(But that is what you know, right?)

**Comment by d3x42** [comment]
Please try svg-sprite-loader@6.0.4

**Comment by stefpb** [comment]
With svg-sprite-loader@6.0.5 the same error :/

Tell me if there is any way I can support you better. I really want to help as best I can.

**Comment by d3x42** [comment]
@stefpb It would be great if you could create a small repo with the reproduced issue.
