### ISSUE TITLE
Webpack 5 with svg-sprite-loader@6.0.0 compilation error

### ISSUE THREAD

**Issue by shorielov** [JetBrains/svg-sprite-loader#444]
When I try to build a project I got an error: "TypeError: Cannot read property 'tap' of undefined"
Webpack version is 5.26.0

`
TypeError: Cannot read property 'tap' of undefined
    at /node_modules/svg-sprite-loader/lib/plugin.js:82:14
    at Hook.eval [as call] (eval at create (/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:13:1)
    at Hook.CALL_DELEGATE [as _call] (/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/node_modules/webpack/lib/Compiler.js:1014:30)
    at /node_modules/webpack/lib/Compiler.js:1057:29
    at Hook.eval [as callAsync] (eval at create (/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/node_modules/webpack/lib/Compiler.js:1052:28)
    at /node_modules/webpack/lib/Compiler.js:494:12
    at Compiler.readRecords (/node_modules/webpack/lib/Compiler.js:892:11)
    at /node_modules/webpack/lib/Compiler.js:491:11
    at Hook.eval [as callAsync] (eval at create (/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at /node_modules/webpack/lib/Compiler.js:488:20
    at Hook.eval [as callAsync] (eval at create (/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at run (/node_modules/webpack/lib/Compiler.js:485:25)
`

**Comment by joseareland** [comment]
This one happens when using `extract: true` and the SpriteLoaderPlugin. .tap is an utility method on the bluebird JS library.

**Comment by dmnsgn** [comment]
Seems to be actually due to a missing compilation hook here: https://github.com/JetBrains/svg-sprite-loader/blob/89cfdd518c4665e85b0e6c1ababd3c9809dcfd75/lib/plugin.js#L80-L82

**Comment by shorielov** [comment]
@dmnsgn Yes. And I can't create a build with svg-sprite-loader@5.2.1 and webpack@5.26.0

> Module.issuerThere was no ModuleGraph assigned to the Module for backward-compat (Use the new API)
    at /node_modules/webpack/lib/ModuleGraph.js:720:12
    at deprecated (internal/util.js:89:15)
    at Function.getModuleGraphForModule (/node_modules/webpack/lib/ModuleGraph.js:711:18)
    at NormalModule.get issuer [as issuer] (/node_modules/webpack/lib/Module.js:278:22)
    at isModuleShouldBeExtracted (/node_modules/svg-sprite-loader/lib/utils/is-module-should-be-extracted.js:11:20)
    at Array.filter (<anonymous>)
    at new MappedList (/node_modules/svg-sprite-loader/lib/utils/mapped-list.js:42:42)
    at SVGSpritePlugin.afterOptimizeChunks (/node_modules/svg-sprite-loader/lib/plugin.js:179:16)
    at /node_modules/svg-sprite-loader/lib/plugin.js:79:40
    at Hook.eval [as call] (eval at create (/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compilation.seal (/node_modules/webpack/lib/Compilation.js:2295:34)
    at /node_modules/webpack/lib/Compiler.js:1078:20
    at /node_modules/webpack/lib/Compilation.js:2116:4
    at _next2 (eval at create (/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at eval (eval at create (/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:52:1)
    at /node_modules/webpack/lib/FlagDependencyExportsPlugin.js:343:11
    at /node_modules/neo-async/async.js:2830:7
    at Object.each (/node_modules/neo-async/async.js:2850:39)
    at /node_modules/webpack/lib/FlagDependencyExportsPlugin.js:322:18
    at /node_modules/neo-async/async.js:2830:7
    at Object.each (/node_modules/neo-async/async.js:2850:39)

**Comment by d3x42** [comment]
Please try svg-sprite-loader@6.0.2

**Comment by dmnsgn** [comment]
@d3x42 works fine for me 👍

**Comment by shorielov** [comment]
@d3x42 still reproduce the error

webpack: 5.26.0

> /node_modules/webpack/lib/ModuleGraph.js:720
                      throw new Error(
                                        ^

Error: Module.issuerThere was no ModuleGraph assigned to the Module for backward-compat (Use the new API)
    at /node_modules/webpack/lib/ModuleGraph.js:720:12
    at deprecated (internal/util.js:89:15)
    at Function.getModuleGraphForModule (/node_modules/webpack/lib/ModuleGraph.js:711:18)
    at NormalModule.get issuer [as issuer] (/node_modules/webpack/lib/Module.js:278:22)
    at isModuleShouldBeExtracted (/node_modules/svg-sprite-loader/lib/utils/is-module-should-be-extracted.js:11:20)
    at Array.filter (<anonymous>)
    at new MappedList (/node_modules/svg-sprite-loader/lib/utils/mapped-list.js:42:42)
    at SVGSpritePlugin.afterOptimizeChunks (/node_modules/svg-sprite-loader/lib/plugin.js:181:16)
    at /node_modules/svg-sprite-loader/lib/plugin.js:78:40
    at Hook.eval [as call] (eval at create (/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compilation.seal (/node_modules/webpack/lib/Compilation.js:2295:34)
    at /node_modules/webpack/lib/Compiler.js:1078:20
    at /node_modules/webpack/lib/Compilation.js:2116:4
    at _next2 (eval at create (/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at eval (eval at create (/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:52:1)
    at /node_modules/webpack/lib/FlagDependencyExportsPlugin.js:343:11
    at /node_modules/neo-async/async.js:2830:7
    at Object.each (/node_modules/neo-async/async.js:2850:39)
    at /node_modules/webpack/lib/FlagDependencyExportsPlugin.js:322:18
    at /node_modules/neo-async/async.js:2830:7
    at Object.each (/node_modules/neo-async/async.js:2850:39)

**Comment by d3x42** [comment]
@shorielov Could you please share GitHub project with a reproduced issue or your config? It seems to be another issue.

**Comment by shorielov** [comment]
@d3x42 I think it's the same issue https://github.com/JeffreyWay/laravel-mix/issues/2767

You should use the new Module API for getting the issuer.

**Comment by dmnsgn** [comment]
Related to this issue, I am still getting "Use new ChunkGraph API" though: https://github.com/JetBrains/svg-sprite-loader/issues/432 (a deprecation warning)

**Comment by iuscare** [comment]
Getting the same error as shorielov on 6.0.2

```
Error: Module.issuerThere was no ModuleGraph assigned to the Module for backward-compat (Use the new API)
    at /var/www/project/buildchain/node_modules/webpack/lib/ModuleGraph.js:720:12
    at deprecated (internal/util.js:89:15)
    at Function.getModuleGraphForModule (/var/www/project/buildchain/node_modules/webpack/lib/ModuleGraph.js:711:18)
    at NormalModule.get issuer [as issuer] (/var/www/project/buildchain/node_modules/webpack/lib/Module.js:278:22)
    at isModuleShouldBeExtracted (/var/www/project/buildchain/node_modules/svg-sprite-loader/lib/utils/is-module-should-be-extracted.js:11:20)
    at Array.filter (<anonymous>)
    at new MappedList (/var/www/project/buildchain/node_modules/svg-sprite-loader/lib/utils/mapped-list.js:42:42)
    at SVGSpritePlugin.afterOptimizeChunks (/var/www/project/buildchain/node_modules/svg-sprite-loader/lib/plugin.js:181:16)
    at /var/www/project/buildchain/node_modules/svg-sprite-loader/lib/plugin.js:78:40
    at Hook.eval [as call] (eval at create (/var/www/project/buildchain/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:12:1)
    at Hook.CALL_DELEGATE [as _call] (/var/www/project/buildchain/node_modules/tapable/lib/Hook.js:14:14)
    at Compilation.seal (/var/www/project/buildchain/node_modules/webpack/lib/Compilation.js:2295:34)
    at /var/www/project/buildchain/node_modules/webpack/lib/Compiler.js:1078:20
    at /var/www/project/buildchain/node_modules/webpack/lib/Compilation.js:2116:4
    at _next2 (eval at create (/var/www/project/buildchain/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:35:1)
    at eval (eval at create (/var/www/project/buildchain/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:71:1)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
```

**Comment by d3x42** [comment]
Please try svg-sprite-loader@6.0.3

**Comment by iuscare** [comment]
Thanks for the update. I am afraid, but still no success with the ModuleGraph. Same setup, just updated version generates the following stack trace:
```
Error: Module.issuerThere was no ModuleGraph assigned to the Module for backward-compat (Use the new API)
    at /var/www/project/buildchain/node_modules/webpack/lib/ModuleGraph.js:720:12
    at deprecated (internal/util.js:89:15)
    at Function.getModuleGraphForModule (/var/www/project/buildchain/node_modules/webpack/lib/ModuleGraph.js:711:18)
    at NormalModule.get issuer [as issuer] (/var/www/project/buildchain/node_modules/webpack/lib/Module.js:278:22)
    at isModuleShouldBeExtracted (/var/www/project/buildchain/node_modules/svg-sprite-loader/lib/utils/is-module-should-be-extracted.js:11:20)
    at Array.filter (<anonymous>)
    at new MappedList (/var/www/project/buildchain/node_modules/svg-sprite-loader/lib/utils/mapped-list.js:44:42)
    at SVGSpritePlugin.afterOptimizeChunks (/var/www/project/buildchain/node_modules/svg-sprite-loader/lib/plugin.js:188:16)
    at /var/www/project/buildchain/node_modules/svg-sprite-loader/lib/plugin.js:85:40
    at Hook.eval [as call] (eval at create (/var/www/project/buildchain/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:12:1)
    at Hook.CALL_DELEGATE [as _call] (/var/www/project/buildchain/node_modules/tapable/lib/Hook.js:14:14)
    at Compilation.seal (/var/www/project/buildchain/node_modules/webpack/lib/Compilation.js:2299:34)
    at /var/www/project/buildchain/node_modules/webpack/lib/Compiler.js:1080:20
    at /var/www/project/buildchain/node_modules/webpack/lib/Compilation.js:2120:4
    at _next2 (eval at create (/var/www/project/buildchain/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:35:1)
    at eval (eval at create (/var/www/project/buildchain/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:71:1)
npm ERR! code ELIFECYCLE
```

**Comment by d3x42** [comment]
@iuscare svg-sprite-loader@6.0.5. It works on test project, I hope it'll solve your issue

**Comment by iuscare** [comment]
@d3x42 yay! This seems to work. Great! I am going to test it the following days, but on first look it seems that the issue can be closed for me. Thank you so much, I really appreciate your effort.
