### ISSUE TITLE
incompatible PostCSS versions `svg-sprite-loader` >> `svg-baker` >> `postcss-prefix-selector` ("Error: [object Object] is not a PostCSS plugin")

### ISSUE THREAD

**Issue by danielweck** [JetBrains/svg-sprite-loader#469]
`svg-sprite-loader` depends on `svg-baker` which in turn depends on `postcss-prefix-selector`.
Problem: PostCSS v5 is not compatible with PostCSS v8

NPM dependencies tracing:

https://github.com/JetBrains/svg-mixer/blob/68f4f77f780d64883e26719a882c9893888c7099/packages/svg-baker/package.json#L23-L24

https://github.com/RadValentin/postcss-prefix-selector/blob/1ddbaf925256b4d6593ebae5a9d07b22c4273a21/package.json#L14

Code references:

https://github.com/JetBrains/svg-mixer/blob/68f4f77f780d64883e26719a882c9893888c7099/packages/svg-baker/lib/transformations/prefix-style-selectors.js#L3-L4

Compilation stacktrace (WebPack):

```
    Module build failed (from ./node_modules/svg-sprite-loader/lib/loader.js):
    Error: [object Object] is not a PostCSS plugin
        at Processor.normalize (/ROOT/node_modules/svg-baker/node_modules/postcss/lib/processor.js:145:15)
        at Processor.use (/ROOT/node_modules/svg-baker/node_modules/postcss/lib/processor.js:86:45)
        at /ROOT/node_modules/svg-baker/lib/transformations/prefix-style-selectors.js:22:10
        at tryCatcher (/ROOT/node_modules/bluebird/js/release/util.js:16:23)
        at MappingPromiseArray._promiseFulfilled (/ROOT/node_modules/bluebird/js/release/map.js:68:38)
        at MappingPromiseArray.PromiseArray._iterate (/ROOT/node_modules/bluebird/js/release/promise_array.js:115:31)
        at MappingPromiseArray.init (/ROOT/node_modules/bluebird/js/release/promise_array.js:79:10)
        at MappingPromiseArray._asyncInit (/ROOT/node_modules/bluebird/js/release/map.js:37:10)
        at _drainQueueStep (/ROOT/node_modules/bluebird/js/release/async.js:97:12)
        at _drainQueue (/ROOT/node_modules/bluebird/js/release/async.js:86:9)
        at Async._drainQueues (/ROOT/node_modules/bluebird/js/release/async.js:102:5)
        at Immediate.Async.drainQueues [as _onImmediate] (/ROOT/node_modules/bluebird/js/release/async.js:15:14)
        at processImmediate (internal/timers.js:462:21)

```

**Comment by danielweck** [comment]
Ah, seems to be fixed here:
https://github.com/RadValentin/postcss-prefix-selector/issues/94
...checking

**Comment by danielweck** [comment]
I confirm that updating `postcss-prefix-selector` to the hotfix release `1.12.0` transitively fixes the `svg-sprite-loader` regression bug.
https://github.com/RadValentin/postcss-prefix-selector/issues/94#issuecomment-902007232

However, I stand by my original comment that depending on incompatible PostCSS versions (directly + transitively) is likely to cause issues in the future.

I am nonetheless closing this issue now, as the bug has effectively been addressed further down in the NPM dependency chain.
